name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'Sources/**'
      - 'Package.swift'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Generate DocC archive
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation \
            --target XamrockCLI \
            --disable-indexing \
            --transform-for-static-hosting \
            --output-path ./docs

      - name: Add CNAME for custom domain
        run: echo "docs.xamrock.com" > ./docs/CNAME

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler pages deploy ./docs \
            --project-name=xamrock-docs \
            --branch=main \
            --commit-dirty=true
