name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'Sources/**'
      - 'Package.swift'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Generate DocC archive
        run: |
          swift package generate-documentation \
            --target XamrockCLI \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path XamrockCLI \
            --output-path ./docs

      - name: Add CNAME for custom domain
        run: echo "docs.xamrock.com" > ./docs/CNAME

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: xamrock-docs
          directory: ./docs
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
