name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'Sources/**'
      - 'Package.swift'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Generate DocC archive
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation \
            --target XamrockCLI \
            --disable-indexing \
            --transform-for-static-hosting \
            --output-path ./docs

      - name: Add CNAME for custom domain
        run: echo "docs.xamrock.com" > ./docs/CNAME

      - name: Create SEO-friendly landing page
        run: |
          cat > ./docs/index-landing.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Xamrock CLI Documentation - AI-Powered Mobile App Testing</title>
            <meta name="description" content="Complete documentation for Xamrock CLI, the AI-powered mobile app testing tool. Learn how to automatically explore iOS apps, generate tests, and integrate with CI/CD.">
            <meta property="og:title" content="Xamrock CLI Documentation">
            <meta property="og:description" content="AI-powered mobile app testing from your terminal. Automatically discover screens, test user flows, and generate comprehensive reports.">
            <meta property="og:type" content="website">
            <meta property="og:url" content="https://docs.xamrock.com">
            <meta name="twitter:card" content="summary_large_image">
            <meta name="twitter:title" content="Xamrock CLI Documentation">
            <meta name="twitter:description" content="AI-powered mobile app testing from your terminal">
            <meta http-equiv="refresh" content="0; url=/documentation/xamrockcli">
            <link rel="canonical" href="https://docs.xamrock.com/documentation/xamrockcli">
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                     display: flex; justify-content: center; align-items: center; height: 100vh;
                     margin: 0; background: #f5f5f7; }
              .container { text-align: center; }
              h1 { font-size: 48px; margin-bottom: 16px; }
              p { font-size: 20px; color: #666; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>Xamrock CLI Documentation</h1>
              <p>Redirecting to documentation...</p>
              <p><a href="/documentation/xamrockcli">Click here if not redirected</a></p>
            </div>
          </body>
          </html>
          EOF
          mv ./docs/index-landing.html ./docs/index.html

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler pages deploy ./docs \
            --project-name=xamrock-docs \
            --branch=main \
            --commit-dirty=true
